apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: subscriber
requires:
  - path: ../pubsub

build:
  tagPolicy:
    inputDigest: { }
  artifacts:
    - image: bibryam/subscriber
      docker:
        dockerfile: Dockerfile
  local: {}

manifests:
  rawYaml:
    - deploy/deployment.yaml

deploy:
  kubectl: {}
  logs:
    prefix: auto
    jsonParse:
      fields: ["time", "msg", "level"]

portForward:
  - resourceType: deployment
    resourceName: subscriber
    namespace: default
    port: 5002
    localPort: 5002
  - resourceType: deployment
    resourceName: subscriber
    namespace: default
    port: 49912
    localPort: 5012