apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      annotations:
        dapr.io/app-id: "publisher"
        dapr.io/app-port: "5001"
        dapr.io/enabled: "true"
        dapr.io/enable-api-logging: "true"
        dapr.io/metrics-port: "49911"
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: bibryam/publisher
          ports:
            - containerPort: 5001
