apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: publisher
requires:
  - path: ../deploy

build:
  tagPolicy:
    inputDigest: { }
  artifacts:
    - image: bibryam/publisher
      docker:
        dockerfile: Dockerfile
  local: {}

manifests:
  rawYaml:
    - deploy/deployment.yaml
    - deploy/service.yaml

deploy:
  kubectl: {}
  logs:
    prefix: auto
    jsonParse:
      fields: ["time", "@timestamp", "level", "msg", "message"]

portForward:
  - resourceType: deployment
    resourceName: publisher
    port: 5001
    localPort: 5001
  - resourceType: deployment
    resourceName: publisher
    port: 9090
    localPort: 5011
  - resourceType: deployment
    resourceName: publisher
    port: 3500
    localPort: 3501